//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Common.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class b_XueLi
    {
        public string XueLi { get; set; }
        public int PaiXu { get; set; }
        public System.DateTime TianJiaShiJian { get; set; }
        public int ZhuangTai { get; set; }
    }
}
